spring:
  data:
    mongodb:
      uri: mongodb://192.168.1.5:27017/luyun
      # uri: mongodb://用户名:密码@服务器IP:端口/数据库名
      # admin 用户认证 url 写法： mongodb://账户:密码%40@ip:端口/数据库名?authSource=admin&authMechanism=SCRAM-SHA-1
  application:
    name: spring-mongodb
logging:
  level:
    root: info
  config: classpath:logback-config.xml
  file:
    path: /tmp/logs
dubbo:
  scan:
    base-packages: com.qiusm.mongodb.service
  protocol:
    name: dubbo
    # dubbo协议缺省端口为20880，rmi协议缺省端口为1099，http和hessian协议缺省端口为80；
    # 如果没有配置port，则自动采用默认端口，如果配置为-1，则会分配一个没有被占用的端口。
    # Dubbo 2.4.0+，分配的端口在协议缺省端口的基础上增长，确保端口段可控
    port: -1
  registry:
    # dubbo服务注册端口，注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔，如：ip:port,ip:port
    # 其中前缀spring-cloud说明：挂载到 Spring Cloud注册中心
    address: nacos://192.168.1.7:8848
    # 关闭注册中心是否启动的相关检查,false表示不检查注册中心是否启动，就不会报错
    check: true
  provider:
    timeout: 10000